### PR TITLE
Work item 328360 - data edits

### PR DESCRIPTION
**Pull request by ktoliver**
Edit column names to be consistent with references in content

Work item [328360](https://dev.azure.com/ceapex/Microsoft%20Learn/_workitems/edit/328360)

@sguthals

### CODE REVIEW

**Comment by sguthals** [comment]
@ktoliver -> This isn't all of them right? I think they were different across code, datasets, and the copy throughout multiple units?

Just checking to make sure you weren't ready for review yet :)

**Comment by ktoliver** [comment]
Hi @sguthals - I can't find the data in GitHub. The units indicate the general source of the data (units [5](https://review.docs.microsoft.com/en-us/learn/modules/plan-moon-mission-using-python-pandas/5-add-modules?branch=pr-en-us-13382) and [8](https://review.docs.microsoft.com/en-us/learn/modules/plan-moon-mission-using-python-pandas/8-prioritize-needed-rocks?branch=pr-en-us-13382)), but I don't see where the data is pulled into the module, so I don't know the source location. Could you give me a pointer? :) 

Some of the phrases I edited (Weight(kg), etc.) are column names that are created in the module, and I changed the code to match the output. Other column names (units 6 and 7--Lunar module (LM), etc.) appear to come from a dataset, which I'll revise if I can find.

**Comment by ktoliver** [comment]
Headers in the https://github.com/sguthals/learnwithdrg/tree/main/OverTheMoon/meteor-showers dir look good; no edits made in the content.

**Comment by sguthals** [comment]
Thank you!!

**Pull request merged**
